# Generated by Django 5.2.8 on 2025-11-15 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id_disponibilidad', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='perfiles.perfiltrabajador')),
            ],
        ),
    ]
