# Generated by Django 5.2.8 on 2025-11-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidad',
            options={'verbose_name': 'Disponibilidad', 'verbose_name_plural': 'Disponibilidades'},
        ),
    ]
