# Generated by Django 5.2.8 on 2025-11-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moderacion',
            fields=[
                ('id_moderacion', models.AutoField(primary_key=True, serialize=False)),
                ('palabras_detectadas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Moderación',
                'verbose_name_plural': 'Moderaciones',
            },
        ),
    ]
