# Generated by Django 5.2.8 on 2025-11-15 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderacion',
            fields=[
                ('id_moderacion', models.AutoField(primary_key=True, serialize=False)),
                ('palabras_detectadas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, limit_choices_to={'rol_base': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderacion', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Moderación',
                'verbose_name_plural': 'Moderaciones',
            },
        ),
    ]
