# Generated by Django 5.2.8 on 2025-11-20 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderacion', '0001_initial'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moderacion',
            name='admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol_base': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderaciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderacion',
            name='servicio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderacion', to='servicios.servicio'),
        ),
    ]
