# Generated by Django 5.2.8 on 2025-11-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilTrabajador',
            fields=[
                ('id_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('experiencia', models.TextField(blank=True, null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('categoria_principal', models.CharField(max_length=120)),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Perfil de trabajador',
                'verbose_name_plural': 'Perfiles de trabajador',
            },
        ),
    ]
