# Generated by Django 5.2.8 on 2025-11-15 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfiltrabajador',
            options={'verbose_name': 'Perfil de trabajador', 'verbose_name_plural': 'Perfiles de trabajador'},
        ),
    ]
