# Generated by Django 5.2.8 on 2025-11-15 23:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfiles', '0002_alter_perfiltrabajador_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id_membresia', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=20)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membresia', to='perfiles.perfiltrabajador')),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
            },
        ),
    ]
