# Generated by Django 5.2.8 on 2025-11-20 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membresias', '0001_initial'),
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='trabajador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membresia', to='perfiles.perfiltrabajador'),
        ),
    ]
